package io.reflectoring.mapper;

import io.reflectoring.entity.UserDb;
import io.reflectoring.entity.UserDbExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserDbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    long countByExample(UserDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    int deleteByExample(UserDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    int insert(UserDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    int insertSelective(UserDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    List<UserDb> selectByExample(UserDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    UserDb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserDb record, @Param("example") UserDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserDb record, @Param("example") UserDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstest
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDb record);
}